apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: mongo-adsat
namePrefix: adsat-
commonLabels:
  environment: adsat
images:
  - name: mongo
    newName: ahmetsaz.azurecr.io/mongo
    newTag: "8.2.3"
