apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: curl-adsat
namePrefix: adsat-
commonLabels:
  environment: adsat
images:
  - name: curlimages/curl
    newName: ahmetsaz.azurecr.io/curl
    newTag: latest
