apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: nginx-adsat
namePrefix: adsat-
commonLabels:
  environment: adsat
images:
  - name: nginx
    newName: ahmetsaz.azurecr.io/nginx
    newTag: 1.28.1-alpine3.23
