apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: curl-dev
namePrefix: dev-

commonLabels:
  environment: dev

images:
  - name: curlimages/curl
    newName: curlimages/curl
    newTag: latest
