apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: mongo-amsat
namePrefix: amsat-
commonLabels:
  environment: amsat
images:
  - name: mongo
    newName: ahmetsaz.azurecr.io/mongo
    newTag: "7.0"
