apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mongo-dev
namePrefix: dev-

commonLabels:
  environment: dev

images:
  - name: mongo
    newName: mongo
    newTag: "7.0"
