apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: busybox-dev
namePrefix: dev-

commonLabels:
  environment: dev

images:
  - name: busybox
    newName: busybox
    newTag: latest
