apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: busybox-amsat
namePrefix: amsat-
commonLabels:
  environment: amsat
images:
  - name: busybox
    newName: ahmetsaz.azurecr.io/busybox
    newTag: "1.36"
