apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: busybox-adsat
namePrefix: adsat-
commonLabels:
  environment: adsat
images:
  - name: busybox
    newName: ahmetsaz.azurecr.io/busybox
    newTag: "1.36"
