apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nginx-amsat
namePrefix: amsat-


commonLabels:
  environment: amsat

images:
  - name: nginx
    newName: nginx
    newTag: alpine
